version: "3.9"

services:
  python:
    container_name: python-fastapi
    image: quay.io/a_horbach/web-services-python-fastapi
    build:
      context: ./python/
      dockerfile: Dockerfile
    volumes:
      - ./python:/home/app
    ports:
      - "8080:8080"
  go:
    container_name: go-http-daemon
    image: quay.io/a_horbach/web-services-go-http-daemon
    build:
      context: ./go/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"