version: "3.9"

services:
  python:
    container_name: python-fastapi
    image: quay.io/a_horbach/web-services-python-fastapi
    build:
      context: ./01-python/
      dockerfile: Dockerfile
    volumes:
      - ./01-python:/home/app
    environment:
      - PORT=8081
    ports:
      - "8081:8081"

  go:
    container_name: go-fiber
    image: quay.io/a_horbach/web-services-go-fiber
    build:
      context: ./02-go/
      dockerfile: Dockerfile
    environment:
      - PORT=8082
    ports:
      - "8082:8082"

  js:
    container_name: nodejs-express
    image: quay.io/a_horbach/web-services-js-express
    build:
      context: ./03-js/
      dockerfile: Dockerfile
    environment:
      - PORT=8083
    ports:
      - "8083:8083"

  ruby:
    container_name: ruby-sinatra
    image: quay.io/a_horbach/web-services-ruby-sinatra
    build:
      context: ./04-ruby/
      dockerfile: Dockerfile
    # TODO: add rerun
    # ref: http://sinatrarb.com/contrib/reloader
    # ref: https://stackoverflow.com/questions/1247125/
    volumes:
      - ./04-ruby:/home/app
    environment:
      - PORT=8084
    ports:
      - "8084:8084"

  rust:
    container_name: rust-warp
    image: quay.io/a_horbach/web-services-rust-warp
    build:
      context: ./05-rust/
      dockerfile: Dockerfile
    environment:
      - PORT=8085
    ports:
      - "8085:8085"

  php:
    container_name: php-slim
    image: quay.io/a_horbach/web-services-php-slim
    build:
      context: ./06-php/
      dockerfile: Dockerfile
    # WARNING: port selection is not working, port specified in CMD / ARGS
    environment:
      - PORT=8086
    ports:
      - "8086:8086"
