version: "3.9"

services:
  python:
    container_name: python-fastapi
    image: quay.io/a_horbach/web-services-python-fastapi
    build:
      context: ./python/
      dockerfile: Dockerfile
    volumes:
      - ./python:/home/app
    ports:
      - "8080:8080"
  go:
    container_name: go-http-daemon
    image: quay.io/a_horbach/web-services-go-http-daemon
    build:
      context: ./go/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  js:
    container_name: nodejs-express
    image: quay.io/a_horbach/web-services-js-express
    build:
      context: ./js/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  ruby:
    container_name: ruby-sinatra
    image: quay.io/a_horbach/web-services-ruby-sinatra
    build:
      context: ./ruby/
      dockerfile: Dockerfile
    # TODO: add rerun
    # ref: http://sinatrarb.com/contrib/reloader
    # ref: https://stackoverflow.com/questions/1247125/
    volumes:
      - ./ruby:/home/app
    ports:
      - "8083:8083"
