---

version: "3"

tasks:
  up:
    cmds:
      - docker compose up

  http:
    desc: Send a http request to all example-web-services
    cmds:
      - |
        targets=$(docker container ls --format json \
          | jq -r 'select(.Networks == "demo-api") | .Ports' \
          | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+'
          )

        for target in "${targets[@]}"; do
          curl -sX GET $target | jq
        done

  cleanup:
    cmds:
      - docker compose down

# ---
  helm-install:
    env:
      HELM_PATH: 00-infra/50-helm
    cmds:
      -  helm upgrade --install demo-api $HELM_PATH -f $HELM_PATH/values.yaml --namespace demo
