---
apiVersion: v1
kind: Service
metadata:
  name: fa
  namespace: default
spec:
  selector:
    app: fa
  ports:
  - port: 8080
    targetPort: 8080
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fa
  namespace: default
spec:
  selector:
    matchLabels:
      app: fa
  template:
    metadata:
      labels:
        app: fa
    spec:
      containers:
        - name: fastapi
          image: karmawow/fastapi:1.0.1
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "75m"
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
                path: /health
                port: 8080
          ports:
            - containerPort: 8080
...
