{{ $app := $.Values.appConfig }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helm-fa.name" . }}
  namespace: default
  labels:
    chart: {{ template "helm-fa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ $app.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ template "helm-fa.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "helm-fa.name" . }}
    spec:
      containers:
        - name: {{ template "helm-fa.name" . }}
          image: "{{ $app.image.repository }}:{{ $app.image.tag }}"
          resources:
{{ toYaml $app.resources | indent 12 }}
          startupProbe:
{{ toYaml $app.startupProbe | indent 12 }}
          livenessProbe:
{{ toYaml $app.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml $app.readinessProbe | indent 12 }}
          {{- if $app.port }}
          ports:
            - containerPort: {{ $app.port }}
          {{ end }}
...
