---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-fa.name" . }}
  namespace: default
spec:
  selector:
    app: {{ template "helm-fa.name" . }}
  ports:
  - port: {{ .Values.appConfig.port }}
    targetPort: {{ .Values.appConfig.port }}
